name: build with cargo in a container

on: workflow_dispatch

jobs:
  cargo-in-a-container:
    runs-on: ubuntu-latest
    steps:
      - uses: DamianReeves/write-file-action
        with:
          path: ./Dockerfile
          contents: |
            FROM docker.io/python:3.9-alpine
            RUN apk add --no-cache build-base cargo ca-certificates libffi-dev musl-dev openssl-dev python3-dev \
             && pip install cryptography
      - uses: redhat-actions/buildah-build@v2
        with:
          containerfiles: |
            ./Dockerfile
          image: cargo-in-a-container
