name: build with cargo in a container

on: workflow_dispatch

jobs:
  cargo-in-a-container:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: redhat-actions/buildah-build@v2
        with:
          containerfiles: |
            ./Dockerfile-cargo-in-a-container
          image: cargo-in-a-container
