name: Test docker-metadata
on: push

jobs:
  test:
    name: Test docker-metadata
    env:
      IMAGE_NAME: deck-chores
    strategy:
      matrix:
        version:
          - "1.2.3"
          - "1.2.3a4"
    runs-on: ubuntu-latest

    steps:
      - run: echo "VERSION=${{ matrix.version }}" >> $GITHUB_ENV
      - run: >
          echo "PRERELEASE=${{ (
          contains('a', env.VERSION) || contains('b', env.VERSION)
          || contains('rc', env.VERSION) || contains('pre', env.VERSION)
          ) }}" >> $GITHUB_ENV
      - name: echo version related variables
        run: |
          echo 'VERSION: ${{ env.VERSION }}'
          echo 'PRERELEASE: ${{ env.PRERELEASE }}'

      - id: docker-metadata
        uses: docker/metadata-action@v3
        with:
          images: ${{ env.IMAGE_NAME }}
          flavor: latest=false
          tags: |
            type=sha,prefix=src-commit-
            type=pep440,pattern={{version}},value=${{ env.VERSION }}
            type=pep440,pattern={{major}},value=${{ env.VERSION }},enable=${{ env.PRERELEASE == 'false' }}
            type=pep440,pattern={{major}}.{{minor}},value=${{ env.VERSION }},enable=${{ env.PRERELEASE == 'false' }}

      # ^ FIXME unexpected result for tags
      # https://github.com/funkyfuture/deck-chores/runs/4882715710?check_suite_focus=true#step:8:42

      - run: |
          echo 'Tags: ${{ steps.docker-metadata.outputs.tags }}'
