name: test evaluation of strings

on:
  push:
  workflow_dispatch:

jobs:
  compare-literal:
    runs-on: ubuntu-latest
    steps:
      - run: echo ${{ github.event_name == "push" }}
  evaluate:
    runs-on: ubuntu-latest
    steps:
      - run: echo ${{ (("tags" == "tags") && "1.3.3") || "" }}
      - run: echo ${{ (("tags" == "") && "") || "1.3.3" }}
