name: test evaluation of strings

on: workflow_dispatch

jobs:
  evaluate:
    runs-on: ubuntu-latest
    steps:
      - run echo ${{ (("tags" == "tags") && "1.3.3") || "" }}
      - run echo ${{ (("tags" == "") && "") || "1.3.3" }}
